name: Run

on:
  schedule:
    - cron: "*/5 * * * *"

  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@main
        with:
          node-version: latest

      - run: npm i -g bun @antfu/ni

      - name: Install dependencies
        run: ni

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        uses: coactions/setup-xvfb@main
        with:
          run: bunx playwright test
