name: Run

on:
  schedule:
    - cron: "* * * * *"

  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        uses: coactions/setup-xvfb@main
        with:
          run: bunx playwright test
